# Generated by Django 2.1.5 on 2019-02-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('mus_tc', models.AutoField(primary_key=True, serialize=False)),
                ('mus_ad', models.CharField(max_length=20)),
            ],
        ),
    ]
