# Generated by Django 2.1.5 on 2019-02-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('mus_tc', models.AutoField(primary_key=True, serialize=False)),
                ('hesap_no', models.IntegerField()),
            ],
        ),
    ]
