# Generated by Django 2.1.5 on 2019-02-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksis', '0003_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('mus_tc', models.AutoField(primary_key=True, serialize=False)),
                ('hesap_no', models.IntegerField()),
                ('odeme_turu', models.CharField(max_length=20)),
            ],
        ),
    ]
